### ISSUE TITLE
Error creating service account

### ISSUE THREAD

**Issue by guy-tallon** [nkoson/gke-tutorial#1]
Hi, following the guide, all is well upto `terraform apply`.

Which gives the following error:
`module.cluster.google_project_service.service["cloudresourcemanager.googleapis.com"]: Creating...
module.cluster.google_container_node_pool.custom_nodepool["web-pool"]: Creating...
module.cluster.google_project_service.service["iam.googleapis.com"]: Creating...
module.cluster.google_project_service.service["container.googleapis.com"]: Creating...
module.cluster.google_compute_network.gke-network: Creating...
module.cluster.google_project_iam_custom_role.kubeip: Creating...
module.cluster.google_service_account.kluster: Creating...
module.cluster.google_project_iam_custom_role.kluster: Creating...
module.cluster.google_service_account.kubeip: Creating...
module.cluster.google_container_node_pool.custom_nodepool["ingress-pool"]: Creating...
module.cluster.google_compute_address.static-ingress: Creating...

Error: Error creating service account: googleapi: Error 403: Permission iam.serviceAccounts.create is required to perform this operation on project projects/gke-tutorial-261220., forbidden

  on gke/iam.tf line 2, in resource "google_service_account" "kluster":
   2: resource "google_service_account" "kluster" {

`

I gave the *Compute Engine default service account* all the permissions so  I'm not sure what it could be

**Comment by nkoson** [comment]
Hi furby,
It seems that the service account is missing the role "Service Account Admin", preventing it from creating new service accounts. I've also overlooked that in the tutorial. 
Go ahead and add the role to your service account and try running terraform again. Please report here, if it fixes your issue, so I can update the text. Thanks!

**Comment by guy-tallon** [comment]
Hi, thanks for replying. I added a few roles to the  (1098373207348-compute@developer.gserviceaccount.com) account, including the service account admin but no joy.

It looks like the correct permissions to admin IAM. Mysterious

```$ gcloud projects get-iam-policy furbygcp
bindings:
- members:
  - serviceAccount:service-1908098098@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-1908098098@container-engine-robot.iam.gserviceaccount.com
  role: roles/container.serviceAgent
- members:
  - serviceAccount:1908098098-compute@developer.gserviceaccount.com
  - serviceAccount:1908098098@cloudservices.gserviceaccount.com
  - serviceAccount:service-1908098098@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - serviceAccount:1908098098-compute@developer.gserviceaccount.com
  role: roles/iam.roleAdmin
- members:
  - serviceAccount:1908098098-compute@developer.gserviceaccount.com
  role: roles/iam.serviceAccountAdmin
- members:
  - serviceAccount:1908098098-compute@developer.gserviceaccount.com
  role: roles/iam.serviceAccountKeyAdmin
- members:
  - serviceAccount:1908098098-compute@developer.gserviceaccount.com
  role: roles/resourcemanager.projectIamAdmin

**Comment by guy-tallon** [comment]
Created a new service account and the same error. I wonder if I create the accounts manually if that would bypass the errors

**Comment by nkoson** [comment]
I have added some dependency constraints on resources in ba11880381c509b5590cc0c53ae683793761979d 

I was able to run terraform in one go by following the tutorial. Please notice, that I've updated the text to include an addition of an API before running terraform apply. 

There should be no need to add other roles to your compute engine service account than what's stated in the text.

I suggest that you create a new project on GCP and redo the tutorial from start. Please let me know if you run into any issues.

**Comment by guy-tallon** [comment]
Left this for a little while but I wiped out my project and started again. I don't seem to get as far now interestingly.

```
module.cluster.google_project_service.cloudresourcemanager: Creating...
module.cluster.google_compute_network.gke-network: Creating...
module.cluster.google_compute_address.static-ingress: Creating...

Error: Batch "project/testk8s/services:batchEnable" for request "Enable Project Services testk8s: map[cloudresourcemanager.googleapis.com:{}]" returned error: failed to send enable services request: googleapi: Error 403: The caller does not have permission, forbidden

  on gke/main.tf line 11, in resource "google_project_service" "cloudresourcemanager":
  11: resource "google_project_service" "cloudresourcemanager" {
```

I gave the service account the role of Project Owner as I couldn't figure out the missing role. I'm sure there's a way to figure it out.

Regardless, that got me past the permissions problem :)

But, you can't use the `f1-micro` machines for Kubernetes https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#memory_cpu

> Note: f1-micro machines are not supported, because they do not have sufficient memory to run GKE

So I went with **e2-micro** and that seemed to work 🙂 (not sure the cost difference)

**Comment by nkoson** [comment]
f1-micros are definitely not supported (officially), but that won't keep us from using them anyway. That is why I included the "aggressive optimization" chapter in my text. Feel free to open a new issue if things have changed to the point where you can't get an f1-micro to work regardless.

**Comment by jawabuu** [comment]
Hey @nkoson excellent work on this.
I tried running the module but it failed due to a timeout with this error
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/649
`Error: Error waiting for creating GKE NodePool: All cluster resources were brought up, but: only 0 nodes out of 1 have registered; cluster may be unhealthy.`
It seems the default node-pool is not deleted which is probably a bug with gke.
This happens consistently, can you test and confirm?

**Comment by jawabuu** [comment]
Also tested f1-micro with a different module and it returns error
`Node pools of f1-micro are not supported..`
