### ISSUE TITLE
error creating node pools

### ISSUE THREAD

**Issue by ip999** [nkoson/gke-tutorial#2]
Firstly, thanks for this. Exactly what I was looking for.

When running (via terraform.io) it would fail as it appeared to be creating the node-pools at the same time as the cluster, which would fail with a 404 saying the cluster didn't exist. 

I fixed this by making the node_pool resource depend on the cluster, e.g.

`depends_on = [google_container_cluster.k8s]`

in /gke/node_pool.tf

after that, worked like a charm, thanks once again. Now to figure out letsencrypt for traefik....

**Comment by nkoson** [comment]
Thanks for your report. I did some testing and found out that there were also other resources in need of dependency constraints. I've added them in ba11880381c509b5590cc0c53ae683793761979d
