### ISSUE TITLE
broken with traefik image 'latest' (= 'v2.2.7' atm) / works with 'v2.1.9'

### ISSUE THREAD

**Issue by pklaus** [nkoson/gke-tutorial#3]
At the moment, the deployment manifest for traefik specifies the image as `traefik:latest` and that is currently equivalent to `traefik:v2.2.7` (at the time I'm writing this report). When checking the release dates of traefik, I came to the conclusion that you must have been running this on traefik 2.1 when you wrote the blog post on Medium and pushed your code to the repository. Unfortunately, there seem to be changes required fro the v2.2 branch of traefik. For now, a quick workaround is to change [the relevant line](https://github.com/nkoson/gke-tutorial/blob/f57e2a4/k8s/traefik/deployment.yaml#L36) to read `image: traefik:v2.1.9` (currently the newest 2.1.x release) and applying the manifest again to the cluster.

Thank you for your post on Medium and making me use Terraform for the first time. Well done! Greetings from Germany. pklaus

**Comment by nkoson** [comment]
Hi Philipp and thanks for the report! 
As per your suggestion, I have set the tag to v2.1.9, which seems to run without problem in the cluster.
Come think of it, it's probably always a good idea to use fixed version tags when dealing with public images.
