### ISSUE TITLE
Running multiple services

### ISSUE THREAD

**Issue by kyeotic** [nkoson/gke-tutorial#6]
First off: **wow**! This guide, backed by a github repo with functional code, with detailed explanations of the how and why. I can't say this enthusiastically enough, but **_THANK YOU_** 👏 

After setting all of this up (with but a single error) I'm left wondering how to proceed. You have Traefik setup as ingress forwarding everything to nginx. If you were going to add more services on a cluster like this would you handling that routing in Traefik or nginx?

Is Traefik intended to serve as both the replacement for the cluster balancer as well as ingress, or is nginx intended to handle ingress routing to other services/pods?

Does every app that I deploy on this cluster need the `nodeSelector: web-pool`, or is there a way to make that the default so that config is a bit more portable?

**Comment by nkoson** [comment]
Hi and sorry for the delayed response. As you can probably tell, I am not actively monitoring this repository anymore...

To answer your question, in this tutorial project, Traefik is indeed intended to serve as a load balancer and ingress. Nginx is used to serve simple web pages. You could replace Nginx with a nodejs instance, for example. 

The web-pool instance pool is there to keep application instances on cheaper preemptible nodes while the load balancer runs on a dedicated pool. Remember, this is a "cheap" cluster which does not use an external load balancer at all, but an internal one to keep the costs down. Hope this helps.
